export const UserTableData = [
    {
        name:'Meeren Raniga',
        device:'Android',
        status:'Not Verified',
        dob:'24/04/1997',
        Signedup:'Google',
        account:'priyen@gmail.com',
        createdon:'17/02/23',
        time:'23:00:00'
    },
    {
        name:'Shyam Vikram',
        device:'Android',
        status:'In Process',
        dob:'24/04/1996',
        Signedup:'Apple',
        account:'priyen@icloud.com',
        createdon:'17/02/23',
        time:'23:00:00'
    },
    {
        name:'Priyen Raniga',
        device:'IOS',
        status:'Verified',
        dob:'23/05/1999',
        Signedup:'Mobile no.',
        account:'(+44)7766140808',
        createdon:'17/02/23',
        time:'23:00:00'
    },
    {
        name:'Abhishek Chakram',
        device:'IOS',
        status:'Not Verified',
        dob:'23/05/2000',
        Signedup:'Apple',
        account:'Abhiskek@icloud.com',
        createdon:'17/02/23',
        time:'23:00:00'
    }
];

export const SellOrdersData = [
    {
        name:'Meeren Raniga',
        device:'Android',
        value:'£8,000.00',
        value_type:'Fixed Fee: £450.00',
        quantity:'50.454 g',
        quantity_type:'PG Account',
        method:'Receive with bank',
        method_type:'Pending',
        order_type: 'Sell',
        order_acc: 'Goal Account',
        time:'23:11:34',
        date:'17/05/2023',
    },
    {
        name:'Shyam Vikram',
        device:'Android',
        value:'$23,000,000',
        value_type:'Fixed Fee: £450.00',
        quantity:'42.343 g',
        quantity_type:'PG Account',
        method:'Pay With Bank',
        method_type:'Low Risk',
        order_type: 'Sell',
        order_acc: 'Goal Account',
        time:'21:11:33',
        date:'17/05/2023',
    },
    {
        name:'Priyen Raniga',
        device:'IOS',
        value:'$34,000,000',
        value_type:'Fixed Fee: £450.00',
        quantity:'10.456 g',
        quantity_type:'PG Account',
        method:'Card',
        method_type:'Medium Risk',
        order_type: 'Sell',
        order_acc: 'Goal Account',
        time:'23:11:34',
        date:'17/05/2023',
    },
    {
        name:'Abhishek Chakram',
        device:'IOS',
        value:'$2,600,000',
        value_type:'Fixed Fee: £450.00',
        quantity:'50.454 g',
        quantity_type:'PG Account',
        method:'Pay with Bank',
        method_type:'High Risk',
        order_type: 'Sell',
        order_acc: 'Goal Account',
        time:'23:11:34',
        date:'17/05/2023',
    }
];

export const RecurringTableData = [
    {
        name:'Meeren Raniga',
        device:'Android',
        value:'£250.00',
        value_type:'Fixed Fee: £450.00',
        quantity:'34.544 g',
        quantity_type:'PG Account',
        method:'Apple pay',
        method_type:'High Risk',
        order_type: 'Recurring Buy',
        order_acc: 'Daily',
        time:'21:11:33',
        date:'17/05/2023',
    },
    {
        name:'Shyam Vikram',
        device:'Android',
        value:'$23,000,000',
        value_type:'Fixed Fee: £250.00',
        quantity:'42.343 g',
        quantity_type:'PG Account',
        method:'Card',
        method_type:'Low Risk',
        order_type: 'Recurring Buy',
        order_acc: '17th of every Month',
        time:'21:11:33',
        date:'17/05/2023',
    },
    {
        name:'Priyen Raniga',
        device:'IOS',
        value:'$540.00',
        value_type:'Fixed Fee: £74.00',
        quantity:'10.456 g',
        quantity_type:'PG Account',
        method:'Card',
        method_type:'Low Risk',
        order_type: 'Recurring Buy',
        order_acc: 'Weekly on Sunday',
        time:'21:11:33',
        date:'17/05/2023',
    },
    {
        name:'Abhishek Chakram',
        device:'IOS',
        value:'$5000.00',
        value_type:'Fixed Fee: £55.00',
        quantity:'100.000 g',
        quantity_type:'PG Account',
        method:'Barclays',
        method_type:'Medium Risk',
        order_type: 'Recurring Buy',
        order_acc: 'Weekly on Sunday',
        time:'21:11:33',
        date:'17/05/2023',
    }
];

export const BuyTableData = [
    {
        name:'Meeren Raniga',
        device:'Android',
        value:'£8,000.00',
        value_type:'Fixed Fee: £450.00',
        quantity:'50.454 g',
        quantity_type:'PG Account',
        method:'Google pay',
        method_type:'Low Risk',
        order_type: 'BUY',
        order_acc: 'PG Account',
        time:'21:11:33',
        date:'17/05/2023',
    },
    {
        name:'Shyam Vikram',
        device:'Android',
        value:'$23,000,000',
        value_type:'Fixed Fee: £450.00',
        quantity:'42.343 g',
        quantity_type:'PG Account',
        method:'Pay With Bank',
        method_type:'Low Risk',
        order_type: 'BUY',
        order_acc: 'Goal Account',
        time:'21:11:33',
        date:'17/05/2023',
    },
    {
        name:'Priyen Raniga',
        device:'IOS',
        value:'$34,000,000',
        value_type:'Paid',
        quantity:'10.456 g',
        quantity_type:'PG Account',
        method:'Card',
        method_type:'Medium Risk',
        order_type: 'BUY',
        order_acc: 'PG Account',
        time:'21:11:33',
        date:'17/05/2023',
    },
    {
        name:'Abhishek Chakram',
        device:'IOS',
        value:'$2,600,000',
        value_type:'Paid',
        quantity:'50.454 g',
        quantity_type:'PG Account',
        method:'Pay with Bank',
        method_type:'High Risk',
        order_type: 'BUY',
        order_acc: 'PG Account',
        time:'21:11:33',
        date:'17/05/2023',
    }
];

export const ProfileDetails = [
    {
        fullname:'Meeren Raniga',
        email:'priyen@gmail.com',
        phone:'(+44) 7766140808',
        address:'71/A, Fear Street',
        signupmethod:'Google'
    }
];

export const InventoryTableData = [
    {
        name:'Meeren Raniga',
        device:'Super Admin',
        value:'£8,000.00',
        quantity:'50.454 g',
        supplier:'Baird & Co LTD',
        time:'23:11:34',
        date:'17/05/2023',
    },
    {
        name:'Priyen Raniga',
        device:'Super Admin',
        value:'£23,000',
        quantity:'42.343 g',
        supplier:'Baird & Co LTD',
        time:'23:11:34',
        date:'17/05/2023',
    },
    {
        name:'Priyen Raniga',
        device:'Super Admin',
        value:'£33,000',
        quantity:'10.456 g',
        supplier:'Baird & Co LTD',
        time:'23:11:34',
        date:'17/05/2023',
    },
    {
        name:'Priyen Raniga',
        device:'Super Admin',
        value:'£22,000',
        quantity:'100.000 g',
        supplier:'Baird & Co LTD',
        time:'23:11:34',
        date:'17/05/2023',
    }
];
export const goalOrderPopupData= {
    image:'images/goal.png',
    imageHeight: "35px",
    imageWidth:'35px',
    marginTop:'4px',
    order_id:'245045',
    name:'Meeren Raniga',
    signupMethod :'Android',
    time:'23:11:34',
    date:'17/05/2023',
    row1left:'Initial QTY',
    row1right:'25g',
    row2left:'Repeating',
    row2right:'7th of Every Month',
    row3left:'Order Type',
    row3right:'Recurring Buy',
    row4left:'Order',
    row4right:'£150.00 Worth of Gold',
    row5left:'Metfolio Fixed Fee (4%)',
    row5right:'£12.00',
    row6left:'Payment Method',
    row6right:'Credit/Debit Card',
    row7left:'Card Fees (2.7% + 20p)',
    row7right:'£4.00',
    row8left:'Total',
    row8right:'£150.00'
};
export const buyOrderPopupData= {
    image:'images/buy_gold.png',
    imageHeight: "23px",
    imageWidth:'37px',
    marginTop:'10px',
    order_id:'245045',
    name:'Meeren Raniga',
    signupMethod :'Android',
    time:'23:11:34',
    date:'17/05/2023',
    row1left:'Buying For',
    row1right:'Physical Gold Account',
    row2left:'Order Type',
    row2right:'Buy',
    row3left:'Gold Value',
    row3right:'£134.00',
    row4left:'Gold Weight',
    row4right:'25 grams',
    row5left:'Metfolio Fixed Fee (4%)',
    row5right:'£12.00',
    row6left:'Payment Method',
    row6right:'Credit/Debit Card',
    row7left:'Card Fees (2.7% + 20p)',
    row7right:'£4.00',
    row8left:'Total',
    row8right:'£150.00'
};
export const sellOrderPopupData= {
    image:'images/sell_gold.png',
    imageHeight: "30px",
    imageWidth:'30px',
    marginTop:'4px',
    order_id:'245045',
    name:'Meeren Raniga',
    signupMethod :'Android',
    time:'23:11:34',
    date:'17/05/2023',
    row1left:'Selling From',
    row1right:'Physical Gold Account',
    row2left:'Order Type',
    row2right:'Sell',
    row3left:'Gold Value',
    row3right:'£134.00',
    row4left:'Gold Weight',
    row4right:'25 grams',
    row5left:'Metfolio Fixed Fee (2%)',
    row5right:'£12.00',
    row6left:'Deposit Method',
    row6right:'Bank',
    row7left:'Payment Processing Fees',
    row7right:'Free',
    row8left:'Total Deposited',
    row8right:'£150.00'
};
